services:
  app1:
    build: .
    ports:
      - "6000:6000"
    environment:
      REDIS_PORT: 10887
      DATABASE_URL: "mysql://root:root@db:3306/urlshortner"
      DB_USER: root
      DB_PASSWORD: root
      DOCKER_ENV: "APP 1"
    depends_on:
      - redis   
      - db
  app2:
    build: .
    ports:
      - "6001:6000"
    environment:
      REDIS_PORT: 10887
      DATABASE_URL: "mysql://root:root@db:3306/urlshortner"
      DB_USER: root
      DB_PASSWORD: root
      DOCKER_ENV: "APP 2"
    depends_on:
      - redis   
      - db
  app3:
    build: .
    ports:
      - "6002:6000"
    environment:
      REDIS_PORT: 10887
      DATABASE_URL: "mysql://root:root@db:3306/urlshortner"
      DB_USER: root
      DB_PASSWORD: root
      DOCKER_ENV: "APP 3"
    depends_on:
      - redis   
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "10887:10887"
    network_mode: "host"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortner
    ports:
      - "3308:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../urlshortner.sql:/docker-entrypoint-initdb.d/urlshortner.sql
