###
POST http://localhost:6000/api/v1/Users/create
Content-Type: application/json

{
    "username": "Mohammed",
    "email": "amroayman99@gmail.com",
    "password": "123456"
}
###
POST http://localhost/api/v1/Users/login
Content-Type: application/json

{
    "username": "Amr",
    "password": "123456"
} 